#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication gmshToFoam VRFB_FT_H_tailoring.msh
runApplication topoSet
mv log.topoSet log.topoSet1
runApplication refineMesh -dict system/refineMeshDict
mv log.refineMesh log.refineMesh1
runApplication topoSet -dict system/topoSetDict2
mv log.topoSet log.topoSet2
runApplication refineMesh -dict system/refineMeshDict
runApplication topoSet -dict system/topoSetDict3